In [1]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import seaborn as sns
from pandasgui import show

In [62]:
# Read interpolated population series
df_gpw = pd.read_excel('gpw_series.xlsx')

# Fill region ID with unique values
df_gpw['region_id'] = df_gpw.groupby('region').ngroup() + 1

# Keep only relevant colums and rows
df_gpw = df_gpw[['province', 'province_id', 'region', 'region_id', 'year', 'gpw_sum_ipo']]
df_gpw = df_gpw.loc[df_gpw.year <= 2018, :]

# Generate region-level gridded population
df_gpw_reg = df_gpw.groupby(by=['region', 'year']).sum()
df_gpw = df_gpw.set_index(['region', 'year']).join(df_gpw_reg, rsuffix='_reg')

# Keep relevant columns only
df_gpw = df_gpw[['province', 'province_id', 'region_id', 'gpw_sum_ipo', 'gpw_sum_ipo_reg']]

# Calculate province's share to region's population; you will use these as weights for inequality
df_gpw = df_gpw.assign(gpw_sum_ipo_share = lambda x: x.gpw_sum_ipo / x.gpw_sum_ipo_reg)

# Rearrange order of columns and sort rows
df_gpw = df_gpw.reset_index()[['province', 'province_id', 'region', 'region_id', 'year', 'gpw_sum_ipo', 'gpw_sum_ipo_reg', 'gpw_sum_ipo_share']]
df_gpw = df_gpw.sort_values(by=['province_id', 'year']).reset_index(drop=True)

# Export to excel
df_gpw.to_excel('gpw_province_clean.xlsx', index=False)

In [63]:
# Generate table of top 20 most populous provinces
df_gpw.groupby('province').mean().sort_values(by='gpw_sum_ipo', ascending=False).head(20)

                   province_id  region_id  year   gpw_sum_ipo
province
Cebu                        25         12  2009  3.845270e+06
Cavite                      24          7  2009  2.992313e+06
Bulacan                     17          6  2009  2.988431e+06
Negros Occidental           51         11  2009  2.798382e+06
Quezon City               4717          3  2009  2.712927e+06
Laguna                      40          7  2009  2.703477e+06
Pangasinan                  61          4  2009  2.694468e+06
Rizal                       64          7  2009  2.439229e+06
Pampanga                    60          6  2009  2.314359e+06
Batangas                    12          7  2009  2.292547e+06
Davao del Sur               28         15  2009  2.204463e+06
Iloilo                      36         11  2009  2.092926e+06
Nueva Ecija                 55          6  2009  1.927085e+06
Quezon                      62          7  2009  1.909465e+06
Camarines Sur               20         10  2009  1.758777e+06
Zamboanga del Sur           80          9  2009  1.681347e+06
Leyte                       43         13  2009  1.663722e+06
City of Manila             476          3  2009  1.511462e+06
Isabela                     37          5  2009  1.463409e+06
Maguindanao                 44          1  2009  1.399227e+06

In [64]:
# Generate table of bottom 20 most populous provinces
df_gpw.groupby('province').mean().sort_values(by='gpw_sum_ipo', ascending=False).tail(20)

                     province_id  region_id  year    gpw_sum_ipo
province
City of Mandaluyong          475          3  2009  326935.382906
City of Navotas             4710          3  2009  292780.301742
Romblon                       65          8  2009  263437.463153
Abra                           1          2  2009  235023.843460
Catanduanes                   23         10  2009  229336.807721
Marinduque                    45          8  2009  218320.984031
Kalinga                       38          2  2009  201200.706860
Aurora                         8          6  2009  193214.088197
Ifugao                        33          2  2009  190773.345793
Quirino                       63          5  2009  175086.169354
Mountain Province             50          2  2009  153762.351470
Guimaras                      32         11  2009  152315.471362
Biliran                       14         13  2009  150650.105868
City of San Juan            4713          3  2009  142366.665147
Dinagat Islands               30         17  2009  115081.257597
Apayao                         7          2  2009  112231.430897
Siquijor                      68         12  2009   85553.814960
Camiguin                      21         14  2009   77831.127885
Pateros                     4716          3  2009   30951.180284
Batanes                       11          5  2009   15015.882336